# Generated by Django 6.0.7 on 2026-07-18 05:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_metadata', models.TextField()),
                ('wrapped_key', models.TextField()),
                ('sync_version', models.BigIntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_folders', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='vault.vaultfolder')),
            ],
        ),
        migrations.CreateModel(
            name='VaultItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('PASSWORD', 'Password'), ('NOTE', 'Note'), ('DOCUMENT', 'Document'), ('API_KEY', 'API Key'), ('SSH_KEY', 'SSH Key'), ('IDENTITY', 'Identity'), ('BANK_CARD', 'Bank Card'), ('LICENSE', 'License'), ('CERTIFICATE', 'Certificate'), ('CUSTOM', 'Custom'), ('FILE', 'File')], max_length=20)),
                ('ciphertext', models.TextField()),
                ('wrapped_key', models.TextField()),
                ('key_version', models.IntegerField(default=1)),
                ('algorithm', models.CharField(default='AES-256-GCM', max_length=50)),
                ('sync_version', models.BigIntegerField(default=1)),
                ('version', models.IntegerField(default=1)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='vault.vaultfolder')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VaultItemVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ciphertext', models.TextField()),
                ('wrapped_key', models.TextField()),
                ('key_version', models.IntegerField()),
                ('algorithm', models.CharField(max_length=50)),
                ('version', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='vault.vaultitem')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.AddIndex(
            model_name='vaultfolder',
            index=models.Index(fields=['owner', 'sync_version'], name='vault_vault_owner_i_e5352a_idx'),
        ),
        migrations.AddIndex(
            model_name='vaultitem',
            index=models.Index(fields=['owner', 'sync_version'], name='vault_vault_owner_i_1fbe68_idx'),
        ),
        migrations.AddIndex(
            model_name='vaultitem',
            index=models.Index(fields=['item_type'], name='vault_vault_item_ty_024bde_idx'),
        ),
    ]
