# Generated by Django 6.0.7 on 2026-07-18 05:17

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('s3_key', models.CharField(max_length=512)),
                ('thumbnail_s3_key', models.CharField(blank=True, max_length=512, null=True)),
                ('file_hash', models.CharField(max_length=128)),
                ('key_version', models.IntegerField(default=1)),
                ('algorithm', models.CharField(default='AES-256-GCM', max_length=64)),
                ('checksum_algorithm', models.CharField(default='SHA-256', max_length=64)),
                ('chunk_count', models.IntegerField(default=1)),
                ('status', models.CharField(default='uploading', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='chat.message')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('chunk_count', models.IntegerField(default=0)),
                ('completed_chunks', models.IntegerField(default=0)),
                ('upload_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
