# Generated by Django 6.0.7 on 2026-07-18 05:23

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_mediaattachment_uploadsession'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSyncState',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('last_sequence_synced', models.BigIntegerField(default=0)),
                ('sync_version', models.BigIntegerField(default=1)),
                ('last_server_timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_client_timestamp', models.DateTimeField(auto_now_add=True)),
                ('sync_status', models.CharField(default='idle', max_length=32)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('last_full_sync', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DraftMessage',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('ciphertext', models.TextField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='unread_count_cache',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversationmember',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversationmember',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversationmember',
            name='is_muted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversationmember',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='version',
            field=models.BigIntegerField(db_index=True, default=1),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['version'], name='chat_conver_version_56453e_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['last_activity'], name='chat_conver_last_ac_ab750d_idx'),
        ),
        migrations.AddField(
            model_name='devicesyncstate',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_states', to='chat.conversation'),
        ),
        migrations.AddField(
            model_name='devicesyncstate',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_states', to='users.device'),
        ),
        migrations.AddField(
            model_name='draftmessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='chat.conversation'),
        ),
        migrations.AddField(
            model_name='draftmessage',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.device'),
        ),
        migrations.AddField(
            model_name='draftmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='devicesyncstate',
            index=models.Index(fields=['device', 'conversation'], name='chat_device_device__0c5a98_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='devicesyncstate',
            unique_together={('device', 'conversation')},
        ),
        migrations.AlterUniqueTogether(
            name='draftmessage',
            unique_together={('conversation', 'sender', 'device')},
        ),
    ]
