# Generated by Django 6.0.7 on 2026-07-18 14:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_notification_readreceipt_typingstate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='direct_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_direct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversationmember',
            name='last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversationmember',
            name='role',
            field=models.CharField(default='member', max_length=50),
        ),
        migrations.AddField(
            model_name='conversationmember',
            name='unread_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='conversationmember',
            index=models.Index(fields=['user', 'unread_count'], name='chat_conver_user_id_c6f16c_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_direct', True)), fields=('direct_hash',), name='unique_active_direct_conversation'),
        ),
    ]
