# Generated by Django 6.0.7 on 2026-07-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_conversation_deleted_at_conversation_direct_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaattachment',
            name='mime_type',
            field=models.CharField(default='application/octet-stream', max_length=128),
        ),
        migrations.AddField(
            model_name='mediaattachment',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='mime_type',
            field=models.CharField(default='application/octet-stream', max_length=128),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
