# Generated by Django 6.0.7 on 2026-07-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_conversation_disappearing_messages_timer_community_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusview',
            name='reaction',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
