# Generated by Django 6.0.7 on 2026-07-18 06:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sso_enabled', models.BooleanField(default=False)),
                ('idp_metadata_url', models.URLField(blank=True, null=True)),
                ('scim_token', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnterprisePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_mfa', models.BooleanField(default=False)),
                ('require_biometrics', models.BooleanField(default=False)),
                ('session_timeout_minutes', models.IntegerField(default=1440)),
                ('allow_cloud_ai', models.BooleanField(default=True)),
                ('allow_plugins', models.BooleanField(default=True)),
                ('allow_exports', models.BooleanField(default=True)),
                ('allow_clipboard_copy', models.BooleanField(default=True)),
                ('require_device_approval', models.BooleanField(default=False)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='enterprise.organization')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceTrust',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=255, unique=True)),
                ('platform', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('TRUSTED', 'Trusted'), ('PENDING', 'Pending Approval'), ('COMPROMISED', 'Compromised'), ('REVOKED', 'Revoked'), ('RETIRED', 'Retired')], default='PENDING', max_length=20)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ORG_ADMIN', 'Organization Admin'), ('SECURITY_ADMIN', 'Security Admin'), ('COMPLIANCE_OFFICER', 'Compliance Officer'), ('IT_ADMIN', 'IT Administrator'), ('HELPDESK', 'Helpdesk'), ('AUDITOR', 'Auditor'), ('TEAM_ADMIN', 'Team Admin'), ('MEMBER', 'Member'), ('GUEST', 'Guest')], default='MEMBER', max_length=50)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='enterprise.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
