# Generated by Django 6.0.7 on 2026-07-18 06:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('DETECTED', 'Detected'), ('ACKNOWLEDGED', 'Acknowledged'), ('INVESTIGATING', 'Investigating'), ('MITIGATED', 'Mitigated'), ('RESOLVED', 'Resolved'), ('POSTMORTEM', 'Postmortem')], default='DETECTED', max_length=20)),
                ('severity', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('root_cause', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('action', models.CharField(max_length=100)),
                ('severity', models.CharField(db_index=True, default='INFO', max_length=20)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('trace_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceMode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False)),
                ('maintenance_type', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('EMERGENCY', 'Emergency')], default='SCHEDULED', max_length=20)),
                ('scope', models.CharField(choices=[('FULL', 'Full Maintenance'), ('READ_ONLY', 'Read-Only Mode'), ('PARTIAL', 'Partial Component Degradation')], default='FULL', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('estimated_end_time', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(help_text='Public message displayed to users')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
