# Generated by Django 6.0.7 on 2026-07-18 06:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FederatedServer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('server_public_key', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('PENDING', 'Handshake Pending'), ('TRUSTED', 'Trusted'), ('REVOKED', 'Trust Revoked')], default='PENDING', max_length=20)),
                ('negotiated_policy', models.JSONField(default=dict)),
                ('protocol_version', models.CharField(default='v1.0', max_length=10)),
                ('last_handshake', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FederatedDirectory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('federation_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('public_key_bundle', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federation.federatedserver')),
            ],
        ),
    ]
