# Generated by Django 6.0.7 on 2026-07-18 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='federateddirectory',
            name='signed_key_history',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='federatedserver',
            name='capabilities',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='federatedserver',
            name='key_history',
            field=models.JSONField(default=list, help_text='List of previous keys signed by their successors'),
        ),
        migrations.AlterField(
            model_name='federatedserver',
            name='protocol_version',
            field=models.CharField(default='v2.1', max_length=10),
        ),
        migrations.CreateModel(
            name='FederationDeliveryState',
            fields=[
                ('message_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('ACCEPTED', 'Accepted by Local Server'), ('QUEUED', 'Queued for Remote Transmission'), ('DELIVERED', 'Delivered to Remote Server'), ('CLIENT_RECEIVED', 'Received by Remote Client'), ('READ', 'Read by Remote Client')], default='ACCEPTED', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federation.federatedserver')),
            ],
        ),
    ]
