# Generated by Django 6.0.7 on 2026-07-18 06:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0002_federateddirectory_signed_key_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='federationdeliverystate',
            name='state',
            field=models.CharField(choices=[('ACCEPTED', 'Accepted by Local Server'), ('QUEUED', 'Queued for Remote Transmission'), ('DELIVERED', 'Delivered to Remote Server'), ('CLIENT_RECEIVED', 'Received by Remote Client'), ('READ', 'Read by Remote Client'), ('FAILED', 'Delivery Failed'), ('EXPIRED', 'Delivery Expired'), ('REJECTED', 'Delivery Rejected by Policy')], default='ACCEPTED', max_length=20),
        ),
        migrations.CreateModel(
            name='SignedRevocationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revoked_key', models.CharField(max_length=255)),
                ('revocation_signature', models.TextField()),
                ('reason', models.CharField(max_length=255)),
                ('revoked_at', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federation.federatedserver')),
            ],
        ),
    ]
