# Generated by Django 6.0.7 on 2026-07-28 10:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_deleted_at_customuser_display_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('key_bundle_upload', 'Key Bundle Upload'), ('key_bundle_fetch', 'Key Bundle Fetch'), ('prekey_consumed', 'Pre-Key Consumed'), ('device_registered', 'Device Registered'), ('device_removed', 'Device Removed'), ('session_established', 'Session Established'), ('session_destroyed', 'Session Destroyed'), ('login', 'Login'), ('logout', 'Logout'), ('password_change', 'Password Change')], max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.device')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'action', 'created_at'], name='users_audit_user_id_0473ad_idx')],
            },
        ),
        migrations.CreateModel(
            name='OneTimePreKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_key', models.TextField(help_text='Base64 SPKI encoded X25519 public key')),
                ('key_id', models.IntegerField(help_text='Client-assigned key ID')),
                ('is_consumed', models.BooleanField(default=False)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_time_prekeys', to='users.device')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['device', 'is_consumed'], name='users_oneti_device__bbf541_idx')],
            },
        ),
        migrations.CreateModel(
            name='SignedPreKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_key', models.TextField(help_text='Base64 SPKI encoded X25519 public key')),
                ('signature', models.TextField(help_text='Base64 Ed25519 signature of the public key')),
                ('key_id', models.IntegerField(help_text='Client-assigned key ID for rotation tracking')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signed_prekeys', to='users.device')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device', 'is_active'], name='users_signe_device__94b3cb_idx')],
            },
        ),
    ]
