# Generated by Django 6.0.7 on 2026-07-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_aisetting_supportticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimeprekey',
            name='key_id',
            field=models.BigIntegerField(help_text='Client-assigned key ID'),
        ),
        migrations.AlterField(
            model_name='signedprekey',
            name='key_id',
            field=models.BigIntegerField(help_text='Client-assigned key ID for rotation tracking'),
        ),
    ]
